src/Entity/Article.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
#[ApiResource]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $price = null;

    #[ORM\Column]
    private ?int $stock = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $imgUrl = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    /**
     * @var Collection<int, Order>
     */
    #[ORM\ManyToMany(targetEntity: Order::class, inversedBy: 'articles')]
    private Collection $order_article;

    #[ORM\ManyToOne(inversedBy: 'article_merchant')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Merchant $merchant = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?Category $category_article = null;

    public function __construct()
    {
        $this->order_article = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }



    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): static
    {
        $this->stock = $stock;

        return $this;
    }

    public function getImgUrl(): ?string
    {
        return $this->imgUrl;
    }

    public function setImgUrl(?string $imgUrl): static
    {
        $this->imgUrl = $imgUrl;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }


    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, Order>
     */
    public function getOrderArticle(): Collection
    {
        return $this->order_article;
    }

    public function addOrderArticle(Order $orderArticle): static
    {
        if (!$this->order_article->contains($orderArticle)) {
            $this->order_article->add($orderArticle);
        }

        return $this;
    }

    public function removeOrderArticle(Order $orderArticle): static
    {
        $this->order_article->removeElement($orderArticle);

        return $this;
    }

    public function getMerchant(): ?Merchant
    {
        return $this->merchant;
    }

    public function setMerchant(?Merchant $merchant): static
    {
        $this->merchant = $merchant;

        return $this;
    }

    public function isMerchant(User $user): bool
    {
        $merchant = $user->getMerchant();
        return $this->merchant === $merchant;
    }

    public function getCategoryArticle(): ?Category
    {
        return $this->category_article;
    }

    public function setCategoryArticle(?Category $category_article): static
    {
        $this->category_article = $category_article;

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\category;
use App\Entity\Merchant;
use App\Entity\order;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('price')
            ->add('stock')
            ->add('imgUrl')
            ->add('createdAt', DateTimeType::class, [
                'widget' => 'single_text',
                'data' => new \DateTimeImmutable(),
            ])
            ->add('description')
            // ->add('order_article', EntityType::class, [
            //     'class' => Order::class,
            //     'choice_label' => 'id',
            //     'multiple' => true,
            // ])
            ->add('merchant', EntityType::class, [
                'class' => Merchant::class,
                'choice_label' => 'name',
            ])
            ->add('category_article', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'name',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use App\Repository\CategoryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/article')]
class ArticleController extends AbstractController
{
    // #[Route('/', name: 'app_article_index', methods: ['GET'])]
    // public function index(ArticleRepository $articleRepository): Response
    // {
    //     return $this->render('article/index.html.twig', [
    //         'articles' => $articleRepository->findAll(),
    //     ]);
    // }

    #[Route('/', name: 'app_article_index', methods: ['GET'])]
    public function index(Request $request, ArticleRepository $articleRepository, CategoryRepository $categoryRepository): Response
    {
        $search = $request->query->get('search');
        $category = $request->query->get('category');

        $queryBuilder = $articleRepository->createQueryBuilder('a');

        if ($search) {
            $queryBuilder->andWhere('a.name LIKE :search')
                ->setParameter('search', '%' . $search . '%');
        }

        if ($category && is_numeric($category)) {
            $queryBuilder->andWhere('a.category_article = :category')
                ->setParameter('category', (int)$category);
        }

        $articles = $queryBuilder->getQuery()->getResult();
        $categories = $categoryRepository->findAll();

        return $this->render('article/index.html.twig', [
            'articles' => $articles,
            'categories' => $categories,
        ]);
    }


    #[Route('/new', name: 'app_article_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('article/new.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_article_show', methods: ['GET'])]
    public function show(Article $article): Response
    {
        return $this->render('article/show.html.twig', [
            'article' => $article,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_article_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Article $article, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('article/edit.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_article_delete', methods: ['POST'])]
    public function delete(Request $request, Article $article, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $article->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($article);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('app_article_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn">Delete</button>
</form>

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Article
{% endblock %}

{% block content %}
	<h1>Edit Article</h1>

	{{ include('article/_form.html.twig', {'button_label': 'Update'}) }}

	<a href="{{ path('app_article_index') }}">back to list</a>

	{{ include('article/_delete_form.html.twig') }}
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article index
{% endblock %}

{% block content %}
	<h1>Article index</h1>
	<div class="container row mb-1 mt-1">
		<div class="form-group mr-2">
			<form method="get" action="{{ path('app_article_index') }}">
				<div class="row">
					<div class="col-md-4">
						<input type="text" name="search" class="form-control" placeholder="Search by name" value="{{ app.request.query.get('search') }}">
					</div>
					<div class="col-md-4">
						<select name="category" class="form-control">
							<option value="">Select category</option>
							{% for category in categories %}
								<option value="{{ category.id }}" {{ app.request.query.get('category') == category.id ? 'selected' : '' }}>
									{{ category.name }}
								</option>
							{% endfor %}
						</select>
					</div>
					<div class="col-md-4">
						<button type="submit" class="btn btn-primary">Filter</button>
					</div>
				</div>
			</form>
		</div>
	</div>
	<a href="{{ path('app_article_new') }}" class="btn btn-success">Create new</a>
	<div class="row">
		{% for article in articles %}
			<div class="col-md-3">
				<div class="card mb-4">
					<img src="https://picsum.photos/200" class="card-img-top" alt="{{ article.name }}">
					<div class="card-body">
						<h5 class="card-title">{{ article.name }}</h5>
						<p class="card-text">{{ article.description }}</p>
						<p class="card-text">
							<small class="text-muted">Price:
								{{ article.price }}</small>
						</p>
						<p class="card-text">
							<small class="text-muted">Stock:
								{{ article.stock }}</small>
						</p>
						<p class="card-text">
							<small class="text-muted">Category:
								{{ article.categoryArticle.name }}</small>
						</p>
						<p class="card-text">
							<small class="text-muted">Created at:
								{{ article.createdAt ? article.createdAt|date('Y-m-d H:i:s') : '' }}</small>
						</p>
						<a href="{{ path('app_article_show', {'id': article.id}) }}" class="btn btn-primary">Show</a>
						{% if is_granted('IS_AUTHENTICATED_FULLY') and article.isMerchant(app.user) %}
							<a href="{{ path('app_article_edit', {'id': article.id}) }}" class="btn btn-secondary">Edit</a>
						{% endif %}
					</div>
				</div>
			</div>
		{% else %}
			<div class="col-12">
				<div class="alert alert-warning" role="alert">
					No records found.
				</div>
			</div>
		{% endfor %}
	</div>
{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Article{% endblock %}

{% block content %}
    <h1>Create new Article</h1>

    {{ include('article/_form.html.twig') }}

    <a href="{{ path('app_article_index') }}">back to list</a>
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article
{% endblock %}

{% block content %}
	<h1>Article</h1>

	<table class="table">
		<tbody>
			<tr>
				{# <th>Id</th> #}
				<input type='hidden' value='{{ article.id }}'/>
			</tr>
			<tr>
				<th>Name</th>
				<td>{{ article.name }}</td>
			</tr>
			<tr>
				<th>Price</th>
				<td>{{ article.price }}</td>
			</tr>
			<tr>
				<th>Stock</th>
				<td>{{ article.stock }}</td>
			</tr>
			<tr>
				<th>ImgUrl</th>
				<td>{{ article.imgUrl }}</td>
			</tr>
			<tr>
				<th>CreatedAt</th>
				<td>{{ article.createdAt ? article.createdAt|date('Y-m-d H:i:s') : '' }}</td>
			</tr>
			<tr>
				<th>Description</th>
				<td>{{ article.description }}</td>
			</tr>
		</tbody>
	</table>

	<a href="{{ path('app_article_index') }}">back to list</a>

	<a href="{{ path('app_article_edit', {'id': article.id}) }}">edit</a>

	{{ include('article/_delete_form.html.twig') }}
{% endblock %}